# Generated by Django 4.2.2 on 2023-06-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_purchase_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/images')),
                ('name', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_delete', models.BooleanField(default=False)),
                ('is_edit', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
