# Generated by Django 4.2.2 on 2023-06-10 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_delete',
            new_name='is_deleted',
        ),
    ]
