# Generated by Django 4.2.2 on 2023-06-13 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
    ]
